services:
  postgresdb:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=postgresdb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=mydatabase
      - DB_PORT=5432
    stdin_open: true

volumes:
  db: